// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqzyHrKig9ARgMloESJ2CnutUhJQL5DD8',
    appId: '1:673387486415:android:a75a48ee3c756221e9ebba',
    messagingSenderId: '673387486415',
    projectId: 'build-kapok',
    storageBucket: 'build-kapok.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjwckfReWqtXJLxvfgxt-PoHvcpvZucDc',
    appId: '1:673387486415:ios:b2fced6c0fa2c644e9ebba',
    messagingSenderId: '673387486415',
    projectId: 'build-kapok',
    storageBucket: 'build-kapok.firebasestorage.app',
    iosBundleId: 'com.example.kapokApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtM8gB94Sv48iC7CPEhadLtXwlw77OA00',
    appId: '1:673387486415:web:568e88006a73fc00e9ebba',
    messagingSenderId: '673387486415',
    projectId: 'build-kapok',
    authDomain: 'build-kapok.firebaseapp.com',
    storageBucket: 'build-kapok.firebasestorage.app',
    measurementId: 'G-8CCHYHMX5R',
  );

}