// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// IMPORTANT — bundle ID rename pending Firebase Console action.
//
// The iOS and Android Firebase apps in the `build-kapok` Firebase project are
// still registered under the OLD identifiers (com.example.kapokApp /
// com.example.kapok_app). The mobile build targets in this repo have been
// renamed to `org.afairresolution.kapok`. Mobile Firebase init will FAIL at
// runtime until someone with Firebase Console access:
//
//   1. Adds new iOS + Android apps under `org.afairresolution.kapok` in the
//      build-kapok Firebase project.
//   2. Downloads the regenerated GoogleService-Info.plist and
//      google-services.json into app/ios/Runner/ and app/android/app/.
//   3. Re-runs `flutterfire configure` (or hand-updates the const blocks
//      below) to point `android.appId`, `ios.appId`, and `ios.iosBundleId` at
//      the new app records.
//
// Web (Chrome) is unaffected — `web` below references project-level config
// only, not platform-specific app records.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqzyHrKig9ARgMloESJ2CnutUhJQL5DD8',
    appId: '1:673387486415:android:a75a48ee3c756221e9ebba',
    messagingSenderId: '673387486415',
    projectId: 'build-kapok',
    storageBucket: 'build-kapok.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjwckfReWqtXJLxvfgxt-PoHvcpvZucDc',
    appId: '1:673387486415:ios:b2fced6c0fa2c644e9ebba',
    messagingSenderId: '673387486415',
    projectId: 'build-kapok',
    storageBucket: 'build-kapok.firebasestorage.app',
    iosBundleId: 'com.example.kapokApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtM8gB94Sv48iC7CPEhadLtXwlw77OA00',
    appId: '1:673387486415:web:568e88006a73fc00e9ebba',
    messagingSenderId: '673387486415',
    projectId: 'build-kapok',
    authDomain: 'build-kapok.firebaseapp.com',
    storageBucket: 'build-kapok.firebasestorage.app',
    measurementId: 'G-8CCHYHMX5R',
  );

}