/// Privacy Policy for Kapok.
///
/// DRAFT — pending legal review and final attorney sign-off. Placeholders in
/// square brackets (e.g. `[contact email]`) must be filled in before public
/// release.
///
/// Last updated: 2026-05-25
class PrivacyPolicy {
  PrivacyPolicy._();

  static const String lastUpdated = '2026-05-25';

  static const String content = '''
This Privacy Policy describes our policies and procedures on the collection, use and disclosure of your information when you use Kapok (the "Service") and tells you about your privacy rights and how the law protects you.

We use your personal data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.

Interpretation and Definitions

Interpretation

The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

Definitions

For the purposes of this Privacy Policy:
• "Account" means a unique account created for you to access our Service or parts of our Service.
• "Application" means the software program provided by the Company, downloaded by you on any electronic device, named Kapok.
• "Company" (referred to as either "the Company," "we," "us," or "our" in this Agreement) refers to A Fair Resolution, LLC.
• "Country" refers to the United States.
• "Device" means any device that can access the Service such as a computer, a cell phone, or a digital tablet.
• "Personal Data" is any information that relates to an identified or identifiable individual.
• "Service" refers to the Application.
• "Service Provider" means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.
• "Usage Data" refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.
• "You" means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.

Collecting and Using Your Personal Data

Personal Data

While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:
• Email address
• First name and last name
• Phone number
• Address, state, province, ZIP/postal code, city
• Usage Data

Usage Data

Usage Data is collected automatically when using the Service. Usage Data may include information such as your device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.

When you access the Service by or through a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers, and other diagnostic data.

Information Collected While Using the Application

While using our Application, in order to provide features of our Application, we may collect, with your prior permission:
• Information regarding your location.

We use this information to provide features of our Service and to improve and customize our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server, or it may be simply stored on your device. You can enable or disable access to this information at any time through your device settings.

Use of Your Personal Data

The Company may use Personal Data for the following purposes:
• To provide and maintain our Service, including to monitor the usage of our Service.
• To manage your account: to manage your registration as a user of the Service. The Personal Data you provide can give you access to different functionalities of the Service that are available to you as a registered user.
• For the performance of a contract: the development, compliance, and undertaking of any contract entered into with us through the Service.
• To contact you: to contact you by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as in-app push notifications regarding updates or informative communications related to the functionalities, products, or contracted services, including security updates when necessary or reasonable.
• To provide you with news, special offers, and general information about other goods, services, and events which we offer that are similar to those that you have already used or enquired about, unless you have opted not to receive such information.
• To manage your requests: to attend to and manage your requests to us.
• For business transfers: we may use your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding.
• For other purposes: we may use your information for data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and to evaluate and improve our Service.

Sharing Your Personal Data

We may share your personal information in the following situations:
• With Service Providers, to monitor and analyze the use of our Service or to contact you.
• For business transfers, in connection with any merger, sale of Company assets, financing, or acquisition of all or a portion of our business.
• With affiliates, in which case we will require those affiliates to honor this Privacy Policy.
• With business partners, to offer you certain products, services, or promotions.
• With other users, when you share personal information or otherwise interact in the public areas of the Service.
• With your consent, for any other purpose.

Retention of Your Personal Data

The Company will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen security, improve functionality, or where we are legally obligated to retain it for longer.

Transfer of Your Personal Data

Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. This information may be transferred to — and maintained on — computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.

Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer. The Company will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy.

Disclosure of Your Personal Data

Business Transactions
If the Company is involved in a merger, acquisition, or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.

Law Enforcement
Under certain circumstances, the Company may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).

Other Legal Requirements
The Company may disclose your Personal Data in the good faith belief that such action is necessary to:
• Comply with a legal obligation
• Protect and defend the rights or property of the Company
• Prevent or investigate possible wrongdoing in connection with the Service
• Protect the personal safety of users of the Service or the public
• Protect against legal liability

Security of Your Personal Data

The security of your Personal Data is important to us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.

Account Deletion

You can request deletion of your Kapok account from within the app at any time. When you delete your account:
• Your Firebase Authentication record is removed.
• Your user profile document in our database is removed.
• Tasks you created or were assigned to are anonymized: your user identifier is replaced with "deleted_user" so that team members can continue to coordinate around the same disaster-response work without linkage to your identity.
• Your locally-cached data on your device is cleared.

Aggregated analytics data that cannot identify you may be retained for service-improvement purposes.

Analytics

We may use third-party Service Providers to monitor and analyze the use of our Service, including Firebase Analytics and Firebase Crashlytics. These third-party vendors collect, store, use, process, and transfer information about your activity on our Service in accordance with their own privacy policies. You can opt out of analytics from within the app's Settings.

Children's Privacy

Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from anyone under the age of 13 without verification of parental consent, we take steps to remove that information from our servers.

Links to Other Websites

Our Service may contain links to other websites that are not operated by us. If you click on a third-party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.

Changes to This Privacy Policy

We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes are effective when they are posted on this page.

Contact Us

If you have any questions about this Privacy Policy, you can contact us at:

A Fair Resolution, LLC
[contact email — to be filled in before release]
P.O. Box 1223
Amherst, Massachusetts, USA 01004
''';
}
